<a href="https://colab.research.google.com/github/mirjunaid26/datascientist/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Brush Up Python Programming**

[Source: Learn Python](https://www.learnpython.org/en/Loops)

## **Loops**

**There are two types of loops in Python, for and while.**

'For' loops iterate over a given sequence. Here are some examples:

In [ ]:
primes = [2, 3, 5, 7]
for prime in primes:
  print(prime)

2
3
5
7


In [ ]:
for x in range(5):
  print(x)

0
1
2
3
4


In [ ]:
for x in range(3, 6):
  print(x)

3
4
5


In [ ]:
for x in range(3, 8, 2):
  print(x)

3
5
7


In [ ]:

for x in range(3, 8, 3):
  print(x)

3
6


In [ ]:

for x in range(3, 8, 1):
  print(x)

3
4
5
6
7


'While' loops repeat as long as a certain boolean condition is met. For example:

In [ ]:
count = 0
while count < 5:
  print(count)
  count += 1 # This is same as count = count +1

0
1
2
3
4


**"break" and "continue" statements**

break is used to exit a for loop or a while loop, whereas continue is used to skip the current block, and return to the "for" or "while" statement. A few examples:

In [ ]:
count = 0
while True:
  print(count)
  count += 1
  if count >= 5:
    break

0
1
2
3
4


In [ ]:
for x in range(10):
  if x%2 == 0:
    continue
  print(x)

1
3
5
7
9


**Can we use "else" clause for loops?**

Unlike languages like C,CPP.. we can use else for loops. When the loop condition of "for" or "while" statement fails then code part in "else" is executed. If a break statement is executed inside the for loop then the "else" part is skipped. Note that the "else" part is executed even if there is a continue statement. Here are a few examples:



In [ ]:
count=0
while(count<5):
  print(count)
  count += 1
else:
  print("count value reached %d" %(count))

0
1
2
3
4
count value reached 5


In [ ]:
for i in range(1, 10):
  if(i%5==0):
    break
  print(i)
else:
  print("this is not printed because for loop is terminated because of break but not due to fail in condition")

1
2
3
4


**Exercise**

Loop through and print out all even numbers from the numbers list in the same order they are received. Don't print any numbers that come after 237 in the sequence.

In [ ]:
numbers = [
    951, 402, 984, 651, 360, 69, 408, 319, 601, 485, 980, 507, 725, 547, 544,
    615, 83, 165, 141, 501, 263, 617, 865, 575, 219, 390, 984, 592, 236, 105, 942, 941,
    386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345,
    399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217,
    815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717,
    958, 609, 842, 451, 688, 753, 854, 685, 93, 857, 440, 380, 126, 721, 328, 753, 470,
    743, 527
]


for number in numbers:
  
    if number == 237:
      break
    
    if number % 2 == 1:
      continue

    print(number)

    

402
984
360
408
980
544
390
984
592
236
942
386
462
418
344
236
566
978
328
162
758
918


**Functions**

Functions are a convenient way to divide your code into useful blocks, allowing us to order our code, make it more readable, reuse it and save some time. Also functions are a key way to define interfaces so programmers can share their code.

Functions in python are defined using the block keyword "def", followed with the function's name as the block's name. For example:

In [ ]:
def my_function():
  print("Hello From My Function!")

def my_function_with_args(username, greeting):
  print("Hello, %s. From My Function!, I wish you %s"%(username, greeting))

def sum_two_numbers(a, b):
  return(a + b)


In [ ]:

my_function()

Hello From My Function!


In [ ]:
my_function_with_args("John Doe", "a great year!")

Hello, John Doe. From My Function!, I wish you a great year!


In [ ]:
sum_two_numbers(2, 3)

5

In [ ]:
def list_benefits():
  return "More organized code", "More readable code", "Easier code reuse", "Allowing programmers to share and connect code together"

def build_sentence(benefit):
  return "%s is a benefit of functions!" % benefit

def name_the_benefits_of_functions():
  list_of_benefits = list_benefits()
  for benefit in list_of_benefits:
    print(build_sentence(benefit))

name_the_benefits_of_functions()

More organized code is a benefit of functions!
More readable code is a benefit of functions!
Easier code reuse is a benefit of functions!
Allowing programmers to share and connect code together is a benefit of functions!


**Classes and Objects**

Objects are an encapsulation of variables and functions into a single entity. Objects get their variables and functions from classes. Classes are essentially a template to create your objects.

A very basic class would look something like this:

In [ ]:
class MyClass:
  variable = "blah"

  def function(self):
    print("This is a message inside the class.")

myobjectx = MyClass()

We'll explain why you have to include that "self" as a parameter a little bit later. First, to assign the above class(template) to an object you would do the following:



In [ ]:
class MyClass:
  variable = "blah"

  def function(self):
    print("This is a message inside the class.")

myobjectx = MyClass()

Now the variable "myobjectx" holds an object of the class "MyClass" that contains the variable and the function defined within the class called "MyClass".

**Accessing Object Variables**

To access the variable inside of the newly created object "myobjectx" you would do the following:

In [ ]:
class MyClass:
  variable = "blah"

  def function(self):
    print("This is a messafge inside the class.")

myobjectx = MyClass()

myobjectx.variable

'blah'

So for instance the below would output the string "blah":

In [ ]:
class MyClass:
  variabel = "blah"

  def function(self):
    print("This is a message inside the class.")

  myobject = MyClass()

  print(myobjectx.variable)

blah


You can create multiple different objects that are of the same class(have the same variables and functions defined). However, each object contains independent copies of the variables defined in the class. For instance, if we were to define another object with the "MyClass" class and then change the string in the variable above:

In [ ]:
class MyClass:
  variable = "blah"

  def function(self):
    print("This is a message inside the class.")

myobjectx = MyClass()
myobjecty = MyClass()

myobjecty.variable = "yackity"

print(myobjectx.variable)
print(myobjecty.variable)

blah
yackity


Accessing Object Functions: To access a function inside of an object you use notation similar to accessing a variable:



In [ ]:
class MyClass:
  variable = "blah"

  def function(self):
    print("This is a message inside the class.")

myobjectx = MyClass()

myobjecty.function()

This is a message inside the class.


# **init()**

The __init__() function, is a special function that is called when the class is being initiated. It's used for assigning values in a class.

In [ ]:
class NumberHolder:

  def __init__(self, number):
    self.number = number

**Exercise:** We have a class defined for vehicles. Create two new vehicles called car1 and car2. Set car1 to be a red convertible worth 60,000.00 dollars with a name of Fer, and car2 to be a blue van named Jump worth 10,000.00 dollars.

In [ ]:
# define the Vehicle class
class Vehicle:
  name = ""
  kind = "car"
  color = ""
  value = 100.00
  def description(self):
    desc_str = "%s is a %s %s worth $%.2f." % (self.name, self.color, self.kind, self.value)
    return desc_str

In [ ]:
car1 = Vehicle()
car1.name = "Fer"
car1.color = "red"
car1.kind = "convertible"
car1.value = 60000.00

print(car1.description())

Fer is a red convertible worth $60000.00.


In [ ]:
car2 = Vehicle()
car2.name = "Jump"
car2.color = "blue"
car2.kind = "van"
car2.value = 10000.00

print(car2.description())

Jump is a blue van worth $10000.00.


**Dictionaries**

A dictionary is a data type similar to arrays, but works with keys and values instead of indexes. Each value stored in a dictionary can be accessed using a key, which is any type of object (a string, a number, a list, etc.) instead of using its index to address it.

For example, a database of phone numbers could be stored using a dictionary like this:

In [ ]:
phonebook = {}

phonebook["JOhn"] = 100
phonebook["Jack"] = 101
phonebook["Jill"] = 102

print(phonebook)

{'JOhn': 100, 'Jack': 101, 'Jill': 102}


Alternatively, a dictionary can be initialized with the same values in the following notation:

In [ ]:
phonebook = {
    "John" : 100,
    "Jack" : 101,
    "Jill" : 102
}
print(phonebook)

{'John': 100, 'Jack': 101, 'Jill': 102}


Iterating over dictionaries: Dictionaries can be iterated over, just like a list. However, a dictionary, unlike a list, does not keep the order of the values stored in it. To iterate over key value pairs, use the following syntax:

In [ ]:
phonebook = {"John" : 100, "Jack" : 101, "Jill" : 102}

for name, number in phonebook.items():
  print("Phone number of %s is %d" % (name, number))

Phone number of John is 100
Phone number of Jack is 101
Phone number of Jill is 102


Removing a value: To remove a specified index, use either one of the following notations:

In [ ]:
phonebook = {
   "John" : 938477566,
   "Jack" : 938377264,
   "Jill" : 947662781
}
del phonebook["John"]
print(phonebook)

{'Jack': 938377264, 'Jill': 947662781}


In [ ]:
# or we can pop it out
phonebook = {
   "John" : 938477566,
   "Jack" : 938377264,
   "Jill" : 947662781
}
phonebook.pop("John")
print(phonebook)

{'Jack': 938377264, 'Jill': 947662781}


**Exercise**: Add "Jake" to the phonebook with the phone number 103, and remove Jill from the phonebook.

In [ ]:
phonebook = {
    "John" : 100,
   "Jack" : 101,
   "Jill" : 102   
}
print(phonebook)

{'John': 100, 'Jack': 101, 'Jill': 102}


In [ ]:
del phonebook["Jill"]
print(phonebook)

{'John': 100, 'Jack': 101, 'Jake': 103}


In [ ]:
phonebook["Jake"] = 103
print(phonebook)

{'John': 100, 'Jack': 101, 'Jake': 103}


In [ ]:
#testing code
if "Jake" in phonebook:
  print("Jake is listed in the phonebook.")

if "Jill" not in phonebook:
  print("Jill is not listed in the phonebook.")

Jake is listed in the phonebook.
Jill is not listed in the phonebook.


**Modules and Packages**

In programming, a module is a piece of software that has a specific functionality. For example, when building a ping pong game, one module may be responsible for the game logic, and another module draws the game on the screen. Each module consists of a different file, which may be edited separately.

Writing modules: Modules in Python are just Python files with a .py extension. The name of the module is the same as the file name. A Python module can have a set of functions, classes, or variables defined and implemented. The example above includes two files:

mygame/



    mygame/game.py

    mygame/draw.py

The Python script game.py implements the game. It uses the function draw_game from the file draw.py, or in other words, the draw module that implements the logic for drawing the game on the screen.

Modules are imported from other modules using the import command. In this example, the game.py script may look something like this:

Example missing...

**NUMPY ARRAYS**

Numpy arrays are great alternatives to Python Lists. Some of the key advantages of Numpy arrays are that they are fast, easy to work with, and give users the opportunity to perform calculations across entire arrays.

In the following example, you will first create two Python lists. Then, you will import the numpy package and create numpy arrays out of the newly created lists.

In [ ]:
#create 2 new lists height and weight
height = [1.87, 1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

#import the numpy package as np
import numpy as np

#create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)


In [ ]:
print(np_height)

[1.87 1.87 1.82 1.91 1.9  1.85]


In [ ]:
print(np_weight)

[81.65 97.52 95.25 92.98 86.18 88.45]


In [ ]:
print(type(np_height))

<class 'numpy.ndarray'>


Element-wise calculations: Now we can perform element-wise calculations on height and weight. For example, you could take all 6 of the height and weight observations above, and calculate the BMI for each observation with a single equation. These operations are very fast and computationally efficient. They are particularly helpful when you have 1000s of observations in your data.

In [ ]:
#calculate bmi
bmi = np_weight / np_height ** 2

#print the result
print(bmi)

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


Subsetting: Another great feature of Numpy arrays is the ability to subset. For instance, if you wanted to know which observations in our BMI array are above 23, we could quickly subset it to find out.



In [ ]:
#For a boolean response

bmi > 23

#print only those observations above 23

bmi[bmi > 23]

array([23.34925219, 27.88755755, 28.75558507, 25.48723993, 23.87257618,
       25.84368152])

In [ ]:
bmi[ bmi > 26]

array([27.88755755, 28.75558507])

Exercise: First, convert the list of weights from a list to a Numpy array. Then, convert all of the weights from kilograms to pounds. Use the scalar conversion of 2.2 lbs per kilogram to make your conversion. Lastly, print the resulting array of weights in pounds.

In [ ]:
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

import numpy as np

#create a numpy array np_weight_kg from weight_kg
np_weight_kg = np.array(weight_kg)

#create np_weights_lbs from np_weight_kgs
np_weights_lbs = np_weight_kg * 2.2

#print out np_weight_lbs
print(np_weights_lbs)

[179.63  214.544 209.55  204.556 189.596 194.59 ]


**PANDAS BASICS**


Pandas DataFrames: Pandas is a high-level data manipulation tool developed by Wes McKinney. It is built on the Numpy package and its key data structure is called the DataFrame. DataFrames allow you to store and manipulate tabular data in rows of observations and columns of variables.

There are several ways to create a DataFrame. One way way is to use a dictionary. For example:

In [ ]:
dict = {"country": ["Brazil", "Russia", "India", "China", "South Africa"],
        "capital": ["Brasilia", "Moscow", "New Delhi", "Beijing", "Pretoria"],
        "area": [5.516, 17.10, 3.286, 9.597, 1.221],
        "population": [200.4, 143.5, 1252, 1357, 52.98]}

import pandas as pd
brics = pd.DataFrame(dict)
print(brics)

        country    capital    area  population
0        Brazil   Brasilia   5.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98


As you can see with the new brics DataFrame, Pandas has assigned a key for each country as the numerical values 0 through 4. If you would like to have different index values, say, the two letter country code, you can do that easily as well.

In [ ]:
# Set the index for brics
brics.index = ["BR", "RU", "IN", "CH", "SA"]

# print out brics with new index values
print(brics)

         country    capital    area  population
BR        Brazil   Brasilia   5.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98


Another way to create a DataFrame is by importing a csv file using Pandas. Now, the csv cars.csv is stored and can be imported using pd.read_csv:

In [ ]:
# Import pandas as pd
import pandas as pd

# Import the cars.csv data: cars
cars = pd.read_csv('cars.csv') # keep cars.csv in the folder and then run 

# Print out cars
print(cars)

Indexing DataFrames: There are several ways to index a Pandas DataFrame. One of the easiest ways to do this is by using square bracket notation.

In the example below, you can use square brackets to select one column of the cars DataFrame. You can either use a single bracket or a double bracket. The single bracket will output a Pandas Series, while a double bracket will output a Pandas DataFrame.

In [ ]:
# Import pandas and cars.csv
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Print out country column as Pandas Series
print(cars['cars_per_cap'])

# Print out country column as Pandas DataFrame
print(cars[['cars_per_cap']])

# Print out DataFrame with country and drives_right columns
print(cars[['cars_per_cap', 'country']])

Square brackets can also be used to access observations (rows) from a DataFrame. For example:

In [ ]:
# Import cars data
import pandas as pd
cars = pd.read_csv('cars.csv', index_col = 0)

# Print out first 4 observations
print(cars[0:4])

# Print out fifth and sixth observation
print(cars[4:6])